apiVersion: v1
kind: Service

metadata:
  name: aura-perfume-service
  namespace: aura-perfume-ns

spec:
  selector:
    app: aura-perfume

  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000